// File generated by flutterfire_cli
// To regenerate this file, run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcZHOj1YtNiE0z3Sg_UK2QanUo4itw1h0',
    appId: '1:310920437156:web:YOUR_WEB_APP_ID',
    messagingSenderId: '310920437156',
    projectId: 'vintrade-c835b',
    authDomain: 'vintrade-c835b.firebaseapp.com',
    storageBucket: 'vintrade-c835b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcZHOj1YtNiE0z3Sg_UK2QanUo4itw1h0',
    appId: '1:310920437156:android:761a5c8f63d1fd0dd23531',
    messagingSenderId: '310920437156',
    projectId: 'vintrade-c835b',
    storageBucket: 'vintrade-c835b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcZHOj1YtNiE0z3Sg_UK2QanUo4itw1h0',
    appId: '1:310920437156:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '310920437156',
    projectId: 'vintrade-c835b',
    storageBucket: 'vintrade-c835b.firebasestorage.app',
    iosBundleId: 'com.example.vintrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcZHOj1YtNiE0z3Sg_UK2QanUo4itw1h0',
    appId: '1:310920437156:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '310920437156',
    projectId: 'vintrade-c835b',
    storageBucket: 'vintrade-c835b.firebasestorage.app',
    iosBundleId: 'com.example.vintrade',
  );
}
